const express = require("express");
const router = express.Router();
const productRoutes = require("./productRoutes");
const orderRoutes = require("./orderRoutes");
const userRoutes = require("./userRoutes");
const authRoutes = require("./authRoutes");
const categoryRoutes = require("./categoryRoutes");
router.use("/products", productRoutes);
router.use("/orders", orderRoutes);
router.use("/users", userRoutes);
router.use("/auth", authRoutes);
router.use("/categories", categoryRoutes);
module.exports = router;
