/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AdminImport } from './routes/admin'
import { Route as StoreImport } from './routes/_store'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as StoreIndexImport } from './routes/_store/index'
import { Route as AdminProductsImport } from './routes/admin/products'
import { Route as AdminOrdersImport } from './routes/admin/orders'
import { Route as AdminEmployeesImport } from './routes/admin/employees'
import { Route as StoreProductsIndexImport } from './routes/_store/products/index'
import { Route as StoreProductsIdImport } from './routes/_store/products/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const StoreRoute = StoreImport.update({
  id: '/_store',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const StoreIndexRoute = StoreIndexImport.update({
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)

const AdminProductsRoute = AdminProductsImport.update({
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)

const AdminOrdersRoute = AdminOrdersImport.update({
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)

const AdminEmployeesRoute = AdminEmployeesImport.update({
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)

const StoreProductsIndexRoute = StoreProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => StoreRoute,
} as any)

const StoreProductsIdRoute = StoreProductsIdImport.update({
  path: '/products/$id',
  getParentRoute: () => StoreRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/admin/employees': {
      preLoaderRoute: typeof AdminEmployeesImport
      parentRoute: typeof AdminImport
    }
    '/admin/orders': {
      preLoaderRoute: typeof AdminOrdersImport
      parentRoute: typeof AdminImport
    }
    '/admin/products': {
      preLoaderRoute: typeof AdminProductsImport
      parentRoute: typeof AdminImport
    }
    '/_store/': {
      preLoaderRoute: typeof StoreIndexImport
      parentRoute: typeof StoreImport
    }
    '/admin/': {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_store/products/$id': {
      preLoaderRoute: typeof StoreProductsIdImport
      parentRoute: typeof StoreImport
    }
    '/_store/products/': {
      preLoaderRoute: typeof StoreProductsIndexImport
      parentRoute: typeof StoreImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  StoreRoute.addChildren([
    StoreIndexRoute,
    StoreProductsIdRoute,
    StoreProductsIndexRoute,
  ]),
  AdminRoute.addChildren([
    AdminEmployeesRoute,
    AdminOrdersRoute,
    AdminProductsRoute,
    AdminIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
